name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Logging docker"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Ending Login" 
      
    - name: Build docker image
      run: |
        docker build -t havok1177/docker-graphql:0.0.2 .
        docker build -t havok1177/docker-graphql:latest .
        
    - name: Push docker image
      run: |
        docker push havok1177/docker-graphql:0.0.2
        docker push havok1177/docker-graphql:latest
